global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using url_alter_backend.Core.ContributorAggregate;
global using url_alter_backend.UseCases.Contributors.Create;
global using Shouldly;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
